### PR TITLE
Separate shadows for active and inactive windows, and menus, etc.

### PR DESCRIPTION
**Pull request by ghost**
...

### CODE REVIEW

**Comment by DJCrock** [comment]
Haven't worked on this project before, but I thought I'd share my observations.

Tried this out because having different shadows for active and inactive windows is a feature I am also interested in. One thing I noticed is that unless `inactive-opacity` is set to a value less than `1` or `inactive-dim` is set to a value greater than `0`, the values for `shadow-inactive-offset-x`, `shadow-inactive-offset-y`, and `shadow-inactive-radius` are always used (i.e. `shadow-offset-x`, `shadow-offset-y`, and `shadow-radius` are not applied to active windows).

I didn't try out any of the other options you added, but I thought I'd point out what I saw.

**Comment by Bukk12354** [comment]
@garnetius  Hi dude pardon me for asking this but can you take a look at this issue here:https://github.com/chjj/compton/issues/265#issuecomment-189637260 I mean it's been unresolved for over one year now and is bugging me to a huge extent.I have already answered richardgv's questions on the bug but I'm afraid he's not that active anymore on his compton repo.

**Comment by garnetius** [comment]
> Tried this out because having different shadows for active and inactive windows is a feature I am also interested in. One thing I noticed is that unless inactive-opacity is set to a value less than 1 or inactive-dim is set to a value greater than 0, the values for shadow-inactive-offset-x, shadow-inactive-offset-y, and shadow-inactive-radius are always used

Thanks, fixed in https://github.com/garnetius/compton/commit/fc30acda947c3831d608b1d93f27b2dc4bd075f6

@Bukk12354 I'm sorry, but I can't reproduce the problem shown on your screenshot. Actually, it looks to me like it's your window manager problem, not compton's. Try testing in my Steambox (Openbox fork): https://github.com/garnetius/openbox (you have to build it from sources though). If you don't want to build, try vanilla Openbox from your distribution repositories.

**Comment by stevensonmt** [comment]
@garnetius was your fork merged into this repo since your repo seems to be deleted?

**Comment by garnetius** [comment]
@stevensonmt someone did fork my, well, fork, but GitHub is dumb and doesn't show it on its network graph anymore. Apparently, it stops tracking all forks of original fork if that original fork gets deleted, which is quite disturbing.

You might try this [fork](https://github.com/BlackCapCoder/compton) instead. Looks like it is actively maintained.

But compton is essentially abandoned, along with lots of other software for X. I don't recommend wasting your time on this.

Linux on desktop is fundamentally broken: 10 display managers, 20 desktop environments, 1e+124 window managers, dozen of GUI toolkits (written by morons with zero UI design experience), etc.: all incompatible with each other to various degrees.

They've now abandoned perfectly working X and seem to be moving to Wayland these days, which (after several *years* in development) is still incomplete and another broken pile of crap.

I use Linux-based OS headless and when I have to interact with graphical environments for Linux it happens so seldom I don't care what and on top of what it runs. If it's able to log me into desktop, it's perfect.

**Comment by stevensonmt** [comment]
@garnetius Thanks. I'll check to see if that fork included your fixes, which were necessary for some issues I was having.  I don't necessarily agree with your assessment of the Linux desktop.  I think it's currently at an inflection point where a change from X or a reworking of X was needed but at a time when desktop development is a low priority as most focus on mobile platforms.  I don't see the variety of display managers, DEs, and WMs as "broken" but rather as the exemplar of OSS ecosystem.  These days I'm basically only using vim and a browser on my desktop, so maybe I'll give up and go headless too.

**Pull request closed without merging**
