### PR TITLE
Set icon to `compton` in compton.desktop

### PR DESCRIPTION
**Pull request by nejsan**
I propose setting compton's application icon to `compton`, which is not present in any icon sets but could be covered in the future. At the very least it opens the icon up to customization from open source icon sets.

I might open another pull request later with a default application icon for compton, if that's alright.

### CODE REVIEW

**Comment by richardgv** [comment]
See https://github.com/chjj/compton/issues/290#issuecomment-133841261 for the reason why it is commented out and set to `xcompmgr`. Until we actually have a fallback icon that could be distributed with compton, it is probably not a good idea to enable it. Do you have a good one now?

**Comment by nejsan** [comment]
I don't, but I wouldn't mind working on one. Should I open a separate pull request for that or add the icon to this one once I've drawn it?

**Comment by richardgv** [comment]
> I don't, but I wouldn't mind working on one.

That would be great. Thanks!

> Should I open a separate pull request for that or add the icon to this one once I've drawn it?

Just adding it here would be preferred, but if that is tricky, I would not mind you opening another pull request. Please also specify if you need a specific license on your icon, or can accept the license compton uses (MIT). We need to add an installation rule to `Makefile` at the time, by the way.

**Comment by nejsan** [comment]
Ok, I've added an icon of my own creation. I'm fine with it being under the license you're using. Let me know if you have any suggestions for changes!

**Comment by richardgv** [comment]
@nejsan:

Thanks for the icon! I have merged your changes.

As for suggestions:

* The icon is hardly visible at small sizes (like 16x16, a typical size for icons in a menu) and/or with a light theme. We might need a bit more contrast.

* The usage of a gear shape seemingly indicates a configuration utility instead of a X compositor. (user1138 once provided an icon that more closely represents a X compositor on [the wiki page](https://github.com/chjj/compton/wiki/Icons-for-compton) *(I did not mention it previously because I forgot it... Sorry.)*, but due to its relative complexity, it does not too great small sizes.)

**Comment by nejsan** [comment]
You're right, I didn't really think about smaller sizes and themes. I had been toying with the idea of having windows in the icon, but I'd want to find a way to make it look more modern compared to the icons on the wiki.

**Pull request merged**
